package organotiki.mobile.mobilestreet.objects;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by Thanasis on 25/5/2016.
 */
public class Item extends RealmObject {

    @PrimaryKey
    private String ID;
    private ItemCategory myCategory;
    private VAT myVAT;
    private MeasurementUnit myUnit;
    private String Code;
    private String Description;
    private Double Price= 0.0;
    private Double CostPrice = 0.0;

    // Standard getters & setters generated by your IDE…

    public Item() {
    }

    public Item(String ID, ItemCategory category, String code, String description, Double price) {
        this.ID = ID;
        myCategory = category;
        Code = code;
        Description = description;
        Price = price;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public ItemCategory getMyCategory() {
        return myCategory;
    }

    public void setMyCategory(ItemCategory myCategory) {
        this.myCategory = myCategory;
    }

    public String getCode() {
        return Code;
    }

    public void setCode(String code) {
        Code = code;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String decription) {
        Description = decription;
    }

    public Double getPrice() {
        return Price;
    }

    public void setPrice(Double price) {
        Price = price;
    }

    public VAT getMyVAT() {
        return myVAT;
    }

    public void setMyVAT(VAT myVAT) {
        this.myVAT = myVAT;
    }

    public MeasurementUnit getMyUnit() {
        return myUnit;
    }

    public void setMyUnit(MeasurementUnit myMUnit) {
        this.myUnit = myMUnit;
    }

    public Double getCostPrice() {
        return CostPrice;
    }

    public void setCostPrice(Double costPrice) {
        this.CostPrice = costPrice;
    }
}